// app/data.js

export const dummyProducts = [
    {
      id: "1",
      name: "Engineering Textbook",
      price: "5000",
      category: "Books",
      location: "Lagos, Nigeria",
      seller: { name: "Michael Johnson", phone: "+234 801 111 2222" },
      image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=300&fit=crop",
      createdAt: new Date(),
      details: "A comprehensive engineering textbook covering fundamental concepts and advanced topics. Ideal for students and professionals alike.",
    },
    {
      id: "2",
      name: "Laptop Backpack",
      price: "8500",
      category: "Fashion",
      location: "Abuja, Nigeria",
      seller: { name: "Grace Adeyemi", phone: "+234 802 333 4444" },
      image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=300&fit=crop",
      createdAt: new Date(),
      details: "Durable and stylish laptop backpack with multiple compartments for organization. Perfect for students and professionals on the go.",
    },
    {
      id: "3",
      name: "Wireless Earbuds",
      price: "12000",
      category: "Gadgets",
      location: "Ibadan, Nigeria",
      seller: { name: "Chinedu Okafor", phone: "+234 803 555 6666" },
      image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=300&fit=crop",
      createdAt: new Date(),
      details: "High-quality wireless earbuds with noise cancellation and long battery life. Enjoy your music and calls with crystal-clear sound.",
    },
    {
      id: "4",
      name: "Study Desk",
      price: "15000",
      category: "Furniture",
      location: "Enugu, Nigeria",
      seller: { name: "Fatima Bello", phone: "+234 804 777 8888" },
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=300&fit=crop",
      createdAt: new Date(),
      details: "Ergonomic study desk with ample workspace and storage options. Designed to enhance productivity and comfort during study sessions.",
    },
    {
      id: "5",
      name: "Scientific Calculator",
      price: "3500",
      category: "Gadgets",
      location: "Kano, Nigeria",
      seller: { name: "Ahmed Musa", phone: "+234 805 999 0000" },
      image: "https://images.unsplash.com/photo-1611125832047-1d7ad1e8e48f?w=400&h=300&fit=crop",
      createdAt: new Date(),
      details: "Advanced scientific calculator with multiple functions and a user-friendly interface. Ideal for students in engineering and science fields.",
    },
    {
      id: "6",
      name: "Campus Hoodie",
      price: "6500",
      category: "Fashion",
      location: "Port Harcourt, Nigeria",
      seller: { name: "Blessing Ojo", phone: "+234 806 123 4567" },
      image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400&h=300&fit=crop",
      createdAt: new Date(),
      details: "Comfortable and trendy campus hoodie made from high-quality materials. Perfect for staying warm during chilly campus days.",
    },
    {
      id: "7",
      name: "Physics Lab Manual",
      price: "2500",
      category: "Books",
      location: "Benin, Nigeria",
      seller: { name: "Uche Eze", phone: "+234 807 333 1212" },
      image: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=400&h=300&fit=crop",
      createdAt: new Date(),
      details: "Comprehensive physics lab manual with detailed experiments and explanations. A valuable resource for students conducting laboratory work.",
    },
    {
      id: "8",
      name: "Study Lamp",
      price: "4500",
      category: "Others",
      location: "Jos, Nigeria",
      seller: { name: "Maryam Sani", phone: "+234 808 456 7890" },
      image: "https://images.unsplash.com/photo-1565636192335-23b6b1a7b8c6?w=400&h=300&fit=crop",
      createdAt: new Date(),
      details: "Adjustable study lamp with bright LED lighting and a sleek design. Provides optimal illumination for reading and studying.",
    },
  ];
  